name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # O la rama desde la que deseas desplegar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the site
      run: |
        npm install
        npm run build  # Reemplaza con el comando de construcciÃ³n adecuado

    - name: List files in build directory
      run: ls -R ./dist/my-app/browser  # Verifica la estructura de directorios

    - name: Add .nojekyll file
      run: echo > ./dist/my-app/browser/.nojekyll  # Ajusta la ruta si es necesario

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/my-app/browser
        publish_branch: gh-pages 